apiVersion: v1
kind: Pod
metadata:
  name: coronapod
  labels:
    appName: corona
spec:
  containers:
    - name: corona
      image: raghravi94/corona:1.0
      ports:
        - name: tomcatport
          containerPort: 8081
          protocol: TCP
      readinessProbe:
        httpGet:
          path: /actuator/health/readiness
          port: 8081
        initialDelaySeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
      livenessProbe:
        httpGet:
          path: /actuator/health/liveness
          port: 8081
        initialDelaySeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
      resources:
        requests:
          cpu: "500m"
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "1024Mi"
      env:
        - name: guidelines.oxygenLevels
          valueFrom:
            configMapKeyRef:
              name: guidelinesconfigmap
              key: oxygenLevels
        - name: guidelines.liters
          valueFrom:
            configMapKeyRef:
              name: guidelinesconfigmap
              key: liters
        - name: guidelines.quarantine
          valueFrom:
            configMapKeyRef:
              name: guidelinesconfigmap
              key: quarantine
        - name: guidelines.temparatureLevels
          valueFrom:
            configMapKeyRef:
              name: guidelinesconfigmap
              key: temparatureLevels
      volumeMounts:
        - name: healthinspectorvol
          mountPath: /config
          readonly: true        
  volumes:
    - name: healthinspectorvol
      configMap:
        name: healthinspectorconfigmap
        items:
          - key: district-healthinspectors.properties
            path: "distriect-healthinspector.properties"
      